### ISSUE TITLE
Design Doc Reviews (Sample State + Backend/Frontend Routes)

### ISSUE THREAD

**Issue by rlim92** [bigcachemoney/TaskxTask#2]
Hey Ray! Design docs looking good, some suggestions below: 

### Sample State:
- [x] `categories` slice of state doesn't need a `user_id`
- [x] add slices of state for `taskers`, `missions`, `reviews`. alternatively, you can place `taskers` in the `users` slice of state with a boolean key of `tasker: true` 

### Backend Routes: 
- [x] make create and show route for `tasks`

### Frontend Routes:
- [ ] Get these in by EOD!

Keep it up!

**Comment by bigcachemoney** [comment]
Added frontend routes but it feels like I'm missing routes. Please take a look when you have a moment.
